export const GET_CHARACTERS_REQUEST='GET_CHARACTERS_REQUEST';
export const GET_CHARACTERS_SUCCESS='GET_CHARACTERS_SUCCESS';
export const GET_CHARACTERS_FAILURE='GET_CHARACTERS_FAILURE';

export const GET_COMICS_SUCCESS = "GET_COMICS_SUCCESS";
export const GET_CHARACTERID_SUCCESS = "GET_CHARACTERID_SUCCESS";